urls.py
from __future__ import unicode_literals
from django.conf.urls import url, include
from . import views

app_name = 'skillcheck'

local_urlpatterns = [
    url(r'^$', views.view_index, name='view_index'),

    url(r'^skillsets/add/$', views.skillset_add, name='skillset_add'),
    url(r'^skillsets/remove/$', views.skillset_remove, name='skillset_remove'),
    url(r'^skillsets/(?P<skillset_id>\d+)/add_skill/$',
        views.skillset_add_skill_view,
        name='skillset_add_skill_view'),
    url(r'^skillsets/(?P<skillset_id>\d+)/remove_skill/$',
        views.skillset_remove_skill,
        name='skillset_remove_skill'),
    url(r'^skillsets/(?P<skillset_id>\d+)/$', views.skillset_edit_view,
        name='skillset_edit_view'),
    url(r'^skillsets/$', views.skillsets_view, name='skillsets_view'),

    url(r'^characters/(?P<character_id>\d+)/update/$',
        views.character_skills_update,
        name='character_skills_update'),
    url(r'^characters/(?P<character_id>\d+)/show/$',
        views.character_skills_show_view,
        name='character_skills_show_view'),

    url(r'^collections/view/$', views.collections_view,
        name='collections_view'),
    url(r'^collections/add/$', views.collection_add,
        name='collection_add'),
    url(r'^collections/remove/$', views.collection_remove,
        name='collection_remove'),
    url(r'^collections/(?P<collection_id>\d+)/edit/$',
        views.collection_edit_view,
        name='collection_edit_view'),
    url(r'^collections/(?P<collection_id>\d+)/add_set/$',
        views.collection_add_set,
        name='collection_add_set'),
    url(r'^collections/(?P<collection_id>\d+)/remove_set/$',
        views.collection_remove_set,
        name='collection_remove_set'),

    url(r'^check/view_result/$', views.check_character_view,
        name='check_character_view'),
    url(r'^check/select/$', views.check_character_selection_view,
        name='check_character_selection_view'),

    url(r'^download/skill_list$', views.download_skills,
        name='download_skills'),
]

urlpatterns = [
    url(r'^skillcheck/', include((local_urlpatterns, 'skillcheck'))),
]

models.py
from __future__ import unicode_literals
from django.db import models
import logging
from allianceauth.eveonline.models import EveCharacter

logger = logging.getLogger(__name__)


class Category(models.Model):
    class Meta:
        default_permissions = ()

    category_id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=254)

    def __repr__(self):
        return f'<{self.__class__.__name__} name={self.name} id={self.category_id}>'


class Group(models.Model):
    class Meta:
        default_permissions = ()

    group_id = models.IntegerField(primary_key=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=254)
    published = models.BooleanField()

    def __repr__(self):
        return f'<{self.__class__.__name__} name={self.name} id={self.group_id}>'


class Skill(models.Model):
    class Meta:
        default_permissions = ()

    skill_id = models.IntegerField(primary_key=True)
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    description = models.TextField()
    name = models.CharField(max_length=254, unique=True)
    published = models.BooleanField()

    def __repr__(self):
        return f'<{self.__class__.__name__} name={self.name} id={self.skill_id}>'


class SkillSet(models.Model):
    class Meta:
        permissions = (
            ('affect_skillset', 'User can change skillsets'),
            ('compare_skillset',
             'Can compare skillsets to characters and view the result'),
        )
        default_permissions = ()

    name = models.CharField(max_length=254)

    def __repr__(self):
        return f'<{self.__class__.__name__} name={self.name} id={self.id}>'


class SkillSetSkill(models.Model):
    class Meta:
        unique_together = (('set', 'skill'),)
        default_permissions = ()

    set = models.ForeignKey(SkillSet, on_delete=models.CASCADE)
    skill = models.ForeignKey(Skill, on_delete=models.CASCADE)
    level = models.PositiveSmallIntegerField()

    def __repr__(self):
        return f'<{self.__class__.__name__} id={self.id}>'


class SkillSetCollection(models.Model):
    class Meta:
        default_permissions = ()

    name = models.CharField(max_length=254)
    skillsets = models.ManyToManyField(SkillSet)

    def __repr__(self):
        return f'<{self.__class__.__name__} name={self.name} id={self.id}>'


class CharacterSkillSet(models.Model):
    class Meta:
        permissions = (
            ('affect_character_skillset',
             'Can load a skillset for his character'),
            ('view_character_skillset',
             'Can view skills of all characters'),
            ('list_in_check',
             'List this users characters in the check selection')
        )
        default_permissions = ()

    character = models.OneToOneField(EveCharacter, on_delete=models.CASCADE,
                                     related_name='+', primary_key=True)
    last_update = models.DateTimeField()

    def __repr__(self):
        return f'<{self.__class__.__name__} charname={self.character.character_name} id={self.id}>'


class CharacterSkillSetSkill(models.Model):
    class Meta:
        unique_together = (('set', 'skill'),)
        default_permissions = ()

    set = models.ForeignKey(CharacterSkillSet, on_delete=models.CASCADE)
    skill = models.ForeignKey(Skill, on_delete=models.CASCADE)
    level = models.PositiveSmallIntegerField()

    def __repr__(self):
        return f'<{self.__class__.__name__} id={self.id}>'

templates/skillcheck/character_skills.html
{% extends "allianceauth/base.html" %}
{% load bootstrap %}
{% load staticfiles %}
{% load i18n %}

{% block title %}Alliance Auth - Skill Check {% endblock %}

{% block page_title %}Character Skills{% endblock page_title %}
{% block extra_css %}

{% endblock extra_css %}

{% block content %}
    {% include 'skillcheck/partials/menu.html' %}
    <div class="col-lg-12">
        <div class="container">
        <div class="row">

            {% for key, value in groups.items %}
            <div class="panel panel-default">
                <div class="panel-heading" data-toggle="collapse" data-target="#group-{{ key }}"><i class="fa  fa-bars"></i> {{ value.0 }}</div>
                <div class="panel-body collapse" id="group-{{ key }}">
                    <table  class="table table-striped table-condensed">
                        <tbody>
                        {% for setskill in value.1 %}
                        <tr{% if setskill.level >= 5 %} class="success"{% endif %}>
                            <td>{{ setskill.skill.name }}</td><td>{{ setskill.level }}</td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
                    
            {% endfor %}
            </tbody>
        </table>
        </div>
        </div>
    </div>
{% endblock content %}

templates/skillcheck/check_selection.html
{% extends "allianceauth/base.html" %}
{% load bootstrap %}
{% load staticfiles %}
{% load i18n %}

{% block title %}Alliance Auth - Skill Check {% endblock %}

{% block page_title %}Select Test Skillset{% endblock page_title %}
{% block extra_css %}

{% endblock extra_css %}

{% block content %}
    {% include 'skillcheck/partials/menu.html' %}
    <div class="col-lg-12">
        <div class="container">
        <!-- Add new skillset row -->
        <div class="row">
            <form class="form-inline" action="{% url 'skillcheck:check_character_view' %}" method="get">
                <select name="character_id" class="form-control">
                {% for char in characters %}
                    <option value="{{ char.character_id }}">{{ char.character_name }}</option>
                {% endfor %}
                </select>
                <select name="collection_id" class="form-control">
                {% for collection in collections %}
                    <option value="{{ collection.id }}">{{ collection.name }}</option>
                {% endfor %}
                </select>
                <button class="btn btn-primary" type="submit">Run Check</button>
            </form>
        </div>
        {% if perms.skillcheck.view_character_skillset %}
        <div class="row">
            <div class="input-group">
            <select id="showskills-charid" name="character_id" class="form-control">
            {% for char in characters %}
                <option value="{% url 'skillcheck:character_skills_show_view' char.character_id %}">{{ char.character_name }}</option>
            {% endfor %}
            </select>
            <span class="input-group-btn">
                <button data-action="show-skills" class="btn btn-primary" type="submit">Show Skills</button>
            </span>
            </div>
        </div>
        {% endif %}
        </div>
    </div>
{% endblock content %}
{% block extra_javascript %}
<script src="{% static 'skillcheck/check_selection.js' %}"></script>
{% endblock extra_javascript %}

templates/skillcheck/collection_edit.html
{% extends "allianceauth/base.html" %}
{% load bootstrap %}
{% load staticfiles %}
{% load i18n %}

{% block title %}Alliance Auth - Skill Check {% endblock %}

{% block page_title %}Select Test Skillset{% endblock page_title %}
{% block extra_css %}

{% endblock extra_css %}

{% block content %}
    {% include 'skillcheck/partials/menu.html' %}
    <div class="col-lg-12">
        <div class="container">
        <!-- Add new skillset row -->
        <div class="row">
            <form class="form-inline" action="{% url 'skillcheck:collection_add_set' collection.id %}" method="post">
                {% csrf_token %}
                <select name="set_name" class="form-control">
                    {% for skillset in skillsets %}
                    <option value="{{ skillset.name }}">{{ skillset.name }}</option>
                    {% endfor %}
                </select>
                <button class="btn btn-primary" type="submit">Add Set to Collection</button>
            </form>
        </div>
        <!-- List skill sets with link to edit page -->
        <div class="row">
            <h4>{{ collection.name }}</h4>
            <table class="table">
                <thead><th>Name</th><th>Remove</th></thead>
                <tbody>
                    {% for skillset in collection.skillsets.all %}
                    <tr id="set-{{ skillset.id }}">
                        <td><a target="_blank" href="{% url 'skillcheck:skillset_edit_view' skillset.id %}">{{ skillset.name }}</a></td>
                        <td><button class="btn btn-danger btn-xs" data-action="remove-set" data-id="{{ skillset.id }}" data-url="{% url 'skillcheck:collection_remove_set' collection.id %}">Remove</button></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        </div>
    </div>
{% endblock content %}
{% block extra_javascript %}
<script src="{% static 'skillcheck/helper.js' %}"></script>
<script src="{% static 'skillcheck/collection_edit.js' %}"></script>
{% endblock extra_javascript %}

templates/skillcheck/collection_result.html
{% extends "allianceauth/base.html" %}
{% load bootstrap %}
{% load staticfiles %}
{% load i18n %}

{% block title %}Alliance Auth - Skillcheck {% endblock %}

{% block page_title %}Character Check{% endblock page_title %}
{% block extra_css %}

{% endblock extra_css %}

{% block content %}
    {% include 'skillcheck/partials/menu.html' %}
    <div class="row">
    <h2>{{ character.character_name }} - {{ collection.name }}</h1>
    {% for result in results %}
    <h4>{{ result.0 }}</h4>
    {% if result.1|length == 0 %}
    <div class="alert alert-success" role="alert">{% trans "PASSED" %}</div>
    {% else %}
    <table class="table">
        <thead><th>Skill Name</th><th>Needed</th><th>Has</th></thead>
        <tbody>
            {% for missing_skill in result.1 %}
            <tr>
            <td>{{missing_skill.0}}</td><td>{{missing_skill.1}}</td><td>{{missing_skill.2}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% endif %}
    {% endfor %}
    </div>
{% endblock content %}

templates/skillcheck/collections.html
{% extends "allianceauth/base.html" %}
{% load bootstrap %}
{% load staticfiles %}
{% load i18n %}

{% block title %}Alliance Auth - Skill Check {% endblock %}

{% block page_title %}Select Test Skillset{% endblock page_title %}
{% block extra_css %}

{% endblock extra_css %}

{% block content %}
    {% include 'skillcheck/partials/menu.html' %}
    <div class="col-lg-12">
        <div class="container">
        <!-- Add new skillset row -->
        <div class="row">
            <form class="form-inline" action="{% url 'skillcheck:collection_add' %}" method="post">
                {% csrf_token %}
                <input class="form-control" type="text" name="collection_name" placeholder="{% trans "Collection Name" %}">
                <button class="btn btn-primary" type="submit">Create New Collection</button>
            </form>
        </div>
        <!-- List skill sets with link to edit page -->
        <div class="row">
            <table class="table">
                <thead>
                <th>Collection Name</th><th>Remove</th>
                </thead>
                <tbody>
                    {% for collection in collections %}
                    <tr id="collection-{{ collection.id }}">
                    <td>
                        <a href="{% url 'skillcheck:collection_edit_view' collection.id %}">{{ collection.name }}</a>
                    </td>
                    <td>
                        <button class="btn btn-danger btn-xs" data-action="remove-col" data-id="{{ collection.id }}" data-url="{% url 'skillcheck:collection_remove' %}">Remove</button>
                    </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        </div>
    </div>
{% endblock content %}
{% block extra_javascript %}
<script src="{% static 'skillcheck/helper.js' %}"></script>
<script src="{% static 'skillcheck/collection_view.js' %}"></script>
{% endblock extra_javascript %}

templates/skillcheck/index.html
{% extends "allianceauth/base.html" %}
{% load bootstrap %}
{% load staticfiles %}
{% load i18n %}

{% block title %}Alliance Auth - Skillcheck {% endblock %}

{% block page_title %}View Chars{% endblock page_title %}
{% block extra_css %}

{% endblock extra_css %}

{% block content %}
    {% include 'skillcheck/partials/menu.html' %}
    <div class="row">
    <table class="table">
    <thead><th>Character</th><th>Update</th><th>Show Skills</th></thead>
    <tbody>
        {% for character in characters %}
        <tr>
            <td>{{character.character_name}}</td>
            <td>
                <form action="{% url 'skillcheck:character_skills_update' character_id=character.character_id %}" method="post" class="form-inline">
                {% csrf_token %}
                <button class="btn btn-danger btn-sm" type="submit">Update Skills</button>
                </form>
            </td>
            <td>
                <a class="btn btn-info btn-sm" href="{% url 'skillcheck:character_skills_show_view' character_id=character.character_id %}">Show Skills</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
    </table>
    </div>
{% endblock content %}

templates/skillcheck/skillset.html
{% extends "allianceauth/base.html" %}
{% load bootstrap %}
{% load staticfiles %}
{% load i18n %}

{% block title %}Alliance Auth - Skill Check {% endblock %}

{% block page_title %}Select Test Skillset{% endblock page_title %}
{% block extra_css %}

{% endblock extra_css %}

{% block content %}
    {% include 'skillcheck/partials/menu.html' %}
    <div class="col-lg-12">
        <div class="container">
        <!-- Add new skillset row -->
        <div class="row">
            <form class="form-inline" action="{% url 'skillcheck:skillset_add' %}" method="post">
                {% csrf_token %}
                <input class="form-control" type="text" name="setname" placeholder="{% trans "Set Name" %}">
                <button class="btn btn-primary" type="submit">Create New Set</button>
            </form>
        </div>
        <!-- List skill sets with link to edit page -->
        <div class="row">
            <table class="table">
                <thead><th>Set Name</th><th>Remove</th></thead>
                <tbody>
                    {% for skillset in skillsets %}
                    <tr id="skillset-{{ skillset.id }}">
                        <td>
                        <a href="{% url 'skillcheck:skillset_edit_view' skillset.id %}">{{ skillset.name }}</a>
                        </td>
                        
                        <td>
                            <button class="btn btn-danger btn-xs" data-action="remove-set" data-id="{{ skillset.id }}" data-url="{% url 'skillcheck:skillset_remove' %}">Remove</button>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        </div>
    </div>
{% endblock content %}
{% block extra_javascript %}
<script src="{% static 'skillcheck/helper.js' %}"></script>
<script src="{% static 'skillcheck/skillset_view.js' %}"></script>
{% endblock extra_javascript %}

templates/skillcheck/skillset_edit.html
{% extends "allianceauth/base.html" %}
{% load bootstrap %}
{% load staticfiles %}
{% load i18n %}

{% block title %}Alliance Auth - Skill Check {% endblock %}

{% block page_title %}Select Test Skillset{% endblock page_title %}
{% block extra_css %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-treeview/1.2.0/bootstrap-treeview.min.css"
 integrity="sha256-ULjuiZ9iqqf97EETp/mZrnLusfOwISiI6AIL0IXShbc=" crossorigin="anonymous" />
{% endblock extra_css %}

{% block content %}
    {% include 'skillcheck/partials/menu.html' %}
    <div class="col-lg-12">
        <div class="container">
        <!-- Add new skillset row -->
        <div class="row">
            <div class="col-sm-6" id="skilltree"></div>
            <div class="col-sm-6">
                <div class="row">
                    <div class="input-group">
                        <input class="form-control" type="number" min="0" max="5" id="skilllevel" placeholder="0...5">
                        <span class="input-group-btn">
                            <button data-action="update-skill" data-setid="{{ skillset.id }}" class="btn btn-primary" id="addskill">Add/Upate Skill</button>
                        </span>
                    </div>
                </div>
                <div class="row">
                    <h4>{{ skillset.name }}</h4>
                    <table class="table" id="skilltable">
                        <thead>
                            <th>Name</th><th>Required Level</th><th>Remove</th>
                        </thead>
                        <tbody>
                            {% for setskill in skillset.skillsetskill_set.all %}
                            <tr id="skill-{{ setskill.skill.skill_id }}">
                                <td>{{ setskill.skill.name }}</td>
                                <td>{{ setskill.level }}</td>
                                <td><button class="btn btn-danger btn-xs" data-action="remove-skill" data-skillid="{{ setskill.skill.skill_id }}" data-setid="{{skillset.id}}">Remove</button></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        </div>
    </div>
{% endblock content %}
{% block extra_javascript %}
<script type="text/javascript">
    {% include 'skillcheck/partials/urls.js' %}
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-treeview/1.2.0/bootstrap-treeview.min.js"
 integrity="sha256-rmZZb5ESAjCE4Al5RfENzQBpw1VbShzLes76aW8c+kc=" crossorigin="anonymous"></script>
<script src="{% static 'skillcheck/helper.js' %}"></script>
<script src="{% static 'skillcheck/skillset_edit.js' %}"></script>
{% endblock extra_javascript %}